spring:
  data:
    mongodb:
      authentication-database: admin
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
  flyway:
    baseline-on-migrate: true
    schemas: phone_number_crud_schema
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:0000}

