CREATE TABLE  phone_number_crud_schema.users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR(255),
    date_of_birth       date,
    first_phone_number  VARCHAR(255),
    second_phone_number VARCHAR(255),
    create_date_time    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

INSERT INTO phone_number_crud_schema.users (name, date_of_birth, first_phone_number, second_phone_number, create_date_time)
VALUES
    ('Beimishev Meirzhan', '2003-05-15', '87774567890', '87016543210', '2023-10-30 08:00:00'),
    ('Ziyabek Orazkhan', '2001-12-11', '87751237890', '87770632799', '2023-10-30 09:15:00'),
    ('Ybrakhim Darkhan', '2002-11-10', '87773335555', '87004446666', '2023-10-30 10:30:00'),
    ('Kanat Sultan', '2004-07-25', '87751112222', '87019991111', '2023-10-30 11:45:00'),
    ('Tynys Aday', '2003-09-05', '87028880000', '87024448888', '2023-10-30 13:00:00'),
    ('Abdrashidov Dias', '2002-01-30', '87763337777', '87773332222', '2023-10-30 14:15:00'),
    ('Abu Dias', '2003-04-12', '87024446666', '87471401383', '2023-10-30 15:30:00'),
    ('Yellubay Erasyl', '2001-08-19', '87017773333', '87011117777', '2023-10-30 16:45:00'),
    ('Kuttybekov Ilyas', '2001-12-04', '87772221111', '87005552222', '2023-10-30 18:00:00'),
    ('Zhumakhanov Almas', '2002-06-29', '87025557777', '87775553333', '2023-10-30 19:15:00');

